# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_product_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='views',
            new_name='viewslala',
        ),
    ]
