# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_remove_product_viewslala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='stores', verbose_name='Image')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
            ],
        ),
    ]
