#-*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default='new store', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogue.Store'),
            preserve_default=False,
        ),
    ]
