# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20170305_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='images/products/2017/03/08'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/products/2017/03/08'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to='images/products/2017/03/08', verbose_name='Original'),
        ),
    ]
