# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import firepit.models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0002_reviewcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('message', models.TextField(max_length=1256)),
            ],
        ),
        migrations.CreateModel(
            name='RequestQuoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=firepit.models.get_quote_image_name, verbose_name='Quote Image')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='firepit.RequestQuote')),
            ],
        ),
    ]
