# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import firepit.models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0004_auto_20170310_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorateSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=1256)),
            ],
        ),
        migrations.CreateModel(
            name='DecorateSpaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=firepit.models.get_space_image_name, verbose_name='Image')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='firepit.DecorateSpace')),
            ],
        ),
    ]
