# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0005_decoratespace_decoratespaceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=1256)),
                ('small_light', models.PositiveIntegerField()),
                ('big_light', models.PositiveIntegerField()),
                ('fan', models.PositiveIntegerField()),
                ('desktop', models.PositiveIntegerField()),
            ],
        ),
    ]
