# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0006_powersolutions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powersolutions',
            options={'verbose_name_plural': 'Power Solutions'},
        ),
        migrations.AlterField(
            model_name='decoratespace',
            name='message',
            field=models.TextField(blank=True, max_length=1256, null=True),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='message',
            field=models.TextField(blank=True, max_length=1256, null=True),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='message',
            field=models.TextField(blank=True, max_length=1256, null=True),
        ),
    ]
