# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0007_auto_20170328_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersolutions',
            name='big_light',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='desktop',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='fan',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='small_light',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
