# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0008_auto_20170328_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersolutions',
            name='hours',
            field=models.CharField(choices=[('3', '3'), ('6', '6'), ('9', '9'), ('12', '12')], default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='big_light',
            field=models.CharField(choices=[('0', '0'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9'), ('>10', '>10')], default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='desktop',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('>5', '>5')], default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='fan',
            field=models.CharField(choices=[('0', '0'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9'), ('>10', '>10')], default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='powersolutions',
            name='small_light',
            field=models.CharField(choices=[('0', '0'), ('1-3', '1-3'), ('4-6', '4-6'), ('7-9', '7-9'), ('>10', '>10')], default='0', max_length=5, null=True),
        ),
    ]
