# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0009_auto_20170328_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=4000, null=True)),
                ('tile_image', models.ImageField(upload_to='home_solutions/tile')),
                ('backgroung_image', models.ImageField(upload_to='home_solutions/background')),
            ],
        ),
    ]
