# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0010_homesolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesolution',
            old_name='backgroung_image',
            new_name='background_image',
        ),
        migrations.AddField(
            model_name='homesolution',
            name='title',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
