# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firepit', '0011_auto_20170424_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesolution',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
