# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20170303_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, default='Telangana', max_length=255, null=True, verbose_name='State'),
        ),
    ]
